#!/usr/bin/python3
# SPDX-FileCopyrightText: 2025 Yusuke Kuga 　　　　　
# SPDX-License-Identifier: GPL-3.0-only
import sys

ans = 0
count = 0
for line in sys.stdin:
    try:
        ans += int(line)
        count += 1
    except:
        try:
            ans += float(line)
            count += 1
        except ValueError:
            continue
average = ans / count
print(f"{average}")
